-- Скрипт создания таблиц
-- Использовать IF NOT EXISTS при создании таблиц и индексов

CREATE TABLE IF NOT EXISTS users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(100) NOT NULL,
    login    VARCHAR(50)  NOT NULL,
    name     VARCHAR(50),
    birthday DATE         NOT NULL
);

CREATE TABLE IF NOT EXISTS friendship
(
    id        INTEGER REFERENCES users (id) ON DELETE CASCADE,
    friend_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
    status    VARCHAR(20),
    CONSTRAINT uq_friendship UNIQUE (id, friend_id)
);

CREATE TABLE IF NOT EXISTS mpa
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(5) NOT NULL
);

CREATE TABLE IF NOT EXISTS films
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(100) NOT NULL,
    description  TEXT,
    release_date DATE,
    duration     INTEGER,
    rate         INTEGER,
    mpa_rating   INTEGER      REFERENCES mpa (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS genres
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS films_genres
(
    film_id  INTEGER REFERENCES films (id) ON DELETE CASCADE,
    genre_id INTEGER REFERENCES genres (id) ON DELETE CASCADE,
    CONSTRAINT uc_films_genre UNIQUE (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS likes
(
    user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
    film_id INTEGER REFERENCES films (id) ON DELETE CASCADE,
    CONSTRAINT uc_likes UNIQUE (user_id, film_id)
);


